AWSTemplateFormatVersion: '2010-09-09'
Decscription: 'AWS CloudFormation Sample Template for creating a web server and a database instance. **WARNING** This template creates an Amazon EC2 instance and an Amazon RDS DB instance. You will be billed for the AWS resources used if you create a stack from this template.'
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-xxxxxxxxxxxxx # Replace with the ID of the AWS Linux AMI
      KeyName: my-key-pair
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd mariadb-server php
          systemctl start httpd
          systemctl enable httpd
          systemctl start mariadb
          systemctl enable mariadb
          echo "<?php phpinfo(); ?>" > /var/www/html/index.php
      SecurityGroupIds:
        - sg-xxxxxxxxxxxxx # Replace with the ID of your security group
      SubnetId: subnet-xxxxxxxxxxxxx # Replace with the ID of your subnet

  MyS3Bucket:
    Type: AWS::S3::Bucket

  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: mariadb
      DBInstanceIdentifier: my-db-instance
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      EngineVersion: 10.4.21
      MasterUsername: admin
      MasterUserPassword: mysecretpassword
      VPCSecurityGroups:
        - Ref: MyDBSecurityGroup

  MyDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow inbound access to the MariaDB database
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0
