AWSTemplateFormatVersion: '2010-09-09'
Description: Single-Instance web-server
Parameters:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap
        - AWSRegionArch2AMI
        - !Ref AWS::Region
        - ami
      InstanceType: t2.micro
      KeyName: !Ref KeyPair
      SecurityGroupIds:
        - !Ref SecurityGroup
  VPC:
    Type: AWS::EC2::VPC
    Properties: {}
Metadata:
  AWS::Composer::Groups:
    Group:
      Label: Group
      Members:
        - VPC
        - Instance